server:
  port: 8002

mybatis:
  type-aliases-package: com.lghonor.springcloud.pojo
  config-location: classpath:mybatis/mybatisconfig.xml
  mapper-locations: classpath:mybatis/mapper/*Mapper.xml
##spring配置
spring:
  security:
    user:
      name: admin
      password: 123456
      roles: admin
  application:
    name: springcloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db02?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: springcloud-provider-dept8002
info:
  app.name: springcloud-lg
  company.name: spingcloud-lghonor
