spring:
  profiles:
    active: dev
---
server:
  port: 7001
spring:
  profiles: dev
  security:
    user:
      name: admin
      password: 123456
      roles: admin
  freemarker:
    prefer-file-system-access: false
eureka:
  instance:
    hostname: eureka7001.com #eureka服务端的实例名称
  client:
    register-with-eureka: false #是否在eureka注册
    fetch-registry: false #为false表示自己就是注册中心
    service-url: #监控页面
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
---
server:
  port: 7001
spring:
  profiles: test
  security:
    user:
      name: admin
      password: 123456
      roles: admin
  freemarker:
    prefer-file-system-access: false
eureka:
  instance:
    hostname: eureka7001.com #eureka服务端的实例名称
  client:
    register-with-eureka: false #是否在eureka注册
    fetch-registry: false #为false表示自己就是注册中心
    service-url: #监控页面
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
