server:
  port: 7001
spring:
  security:
    user:
      name: admin
      password: 123456
      roles: admin
  freemarker:
    prefer-file-system-access: false
eureka:
  instance:
    hostname: eureka7001.com #eureka服务端的实例名称
  client:
    register-with-eureka: false #是否在eureka注册
    fetch-registry: false #为false表示自己就是注册中心
    service-url: #监控页面
      #      单机
      #      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      #       集群
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
      #  server:enable-self-preservation: false 自我保护机制，不建议关闭

