server:
  port: 8102

spring:
  security:
    user:
      name: admin
      password: 123456
      roles: admin
  #eureka配置
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
